### ISSUE TITLE
bammarkduplicates2 on files that have already been duplicate-marked

### ISSUE THREAD

**Issue by jmarshall** [gt1/biobambam#52]
Suppose for example, you have several (lane) BAM/CRAM files that have had duplicates marked, so some records have the FDUP flag set.  You then want to merge the files and mark duplicates properly (at a library level).

The merging and marking can be done in one fell swoop with `bammarkduplicates2 -I=f1.bam -I=f2.bam -I=f3.bam` and so on.

Will `bammarkduplicates2` do the right thing when given reads that already have the FDUP flag set?  If one is lucky, then the second pass of duplicate marking might well leave one of the first pass's unmarked records still unmarked.  However, especially if it's not the same duplicate marking program in both passes, it seems unwise to rely on this.  It seems likely that the second pass may leave unmarked a record that the first pass marked, leading to **all** reads in a putative duplicate set being marked as duplicates.

I looked at the `bammarkduplicates2` code and it appears that it only adds the FDUP flag, and never resets it for any records.  However I couldn't find the code that actually selects records for marking, so I'm unsure whether it guarantees that the record it leaves as the representative is one that is previously unmarked.

In any case, perhaps duplicate marking programs ought to claim complete control of the FDUP flag: explicitly set it for output reads that it is marking as duplicates, and _explicitly reset it_ for output reads that it is leaving behind as the representative record.

**Comment by mcshane** [comment]
There is `bamstreamingmarkduplicates` which has the `resetdupflag` option (off by default).

**Comment by gt1** [comment]
I have changed the behavior of bammarkduplicates and bammarkduplicates2 in version 0.0.190. Previously the FDUP would only ever be added, but never erased by those two programs. Starting from version 0.0.190 the flag will be erased on non duplicate alignments. Btw. the option for (multiple) input files is I=file.bam (without the - in front of the I).

**Comment by jmarshall** [comment]
Excellent, thanks!

Oops and yes indeed re `I=` not having a `-`... just a typo while writing up the issue caused by decades of Unix precedent...

**Comment by keiranmraine** [comment]
I've updated the recipe for downsampling: https://github.com/gt1/biobambam/wiki/Recipes
